@Kodla_Api_HostAddress = http://localhost:5263

@meetupId = 1

###

GET {{Kodla_Api_HostAddress}}/api/meetups

###

GET {{Kodla_Api_HostAddress}}/api/meetups/{{meetupId}}

###

# @name requestAttendee
POST {{Kodla_Api_HostAddress}}/api/meetups/{{meetupId}}/attendies
Content-Type: application/json

{
    "UserName": "Ilya"
}

###

@requestId = {{requestAttendee.response.body.requestId}}

GET {{Kodla_Api_HostAddress}}/api/requests/{{requestId}}
