@Kodla_Api_HostAddress = http://localhost:5263

###

GET {{Kodla_Api_HostAddress}}/api/meetups

###

GET {{Kodla_Api_HostAddress}}/api/bookings

###

@meetupId = 1

POST {{Kodla_Api_HostAddress}}/api/meetups/{{meetupId}}/attendies
Content-Type: application/json

{
    "UserName": "Ilya"
}
