@ApiService_HostAddress = http://localhost:5263


GET {{ApiService_HostAddress}}/api/bookings

###

POST {{ApiService_HostAddress}}/api/bookings/request
Content-Type: application/json

{
    "MeetupId": "HelsinkiJS",
    "UserName": "Ilya"
}